//! WASM bindings module
//!
//! This module provides the JavaScript/TypeScript interface for the rich text editor.
//! All types and functions exposed to JavaScript are defined here.
//!
//! # TypeScript Type Definitions
//!
//! TypeScript type definitions are automatically generated by wasm-bindgen
//! from the JSDoc comments in the implementation files.
//!
//! ## Selection Interface
//!
//! The Selection interface represents a text selection in the document:
//!
//! ```typescript
//! interface Selection {
//!   anchor: number;  // Position where selection started
//!   focus: number;   // Position where selection ends
//! }
//! ```
//!
//! When anchor === focus, the selection is collapsed (just a cursor position).
//! When anchor < focus, the selection is forward.
//! When anchor > focus, the selection is backward.
//!
//! ## Format Types
//!
//! Format types can be either simple strings or objects with additional properties:
//!
//! ```typescript
//! type Format =
//!   | "bold"
//!   | "italic"
//!   | "underline"
//!   | "strikethrough"
//!   | "code"
//!   | { type: "link"; url: string }
//!   | { type: "textColor"; color: string }
//!   | { type: "backgroundColor"; color: string };
//! ```
//!
//! ## Block Types
//!
//! Block types define the structural element type for a range of text:
//!
//! ```typescript
//! type BlockType =
//!   | "paragraph"
//!   | "heading1" | "heading2" | "heading3" | "heading4" | "heading5" | "heading6"
//!   | "bulletList" | "numberedList"
//!   | "blockQuote"
//!   | "codeBlock";
//! ```
//!
//! ## Search Match Interface
//!
//! SearchMatch represents a single match found by the find() method:
//!
//! ```typescript
//! interface SearchMatch {
//!   start: number;  // Starting character offset
//!   end: number;    // Ending character offset
//! }
//! ```
//!
//! ## Search Query Parameters
//!
//! The find() and findAndReplace() methods accept the following parameters:
//! - `pattern`: string - The text pattern to search for
//! - `case_sensitive`: boolean - Whether the search should be case-sensitive
//! - `use_regex`: boolean - Whether to interpret the pattern as a regular expression
//!
//! Example:
//! ```typescript
//! const matches = doc.find("hello", false, false); // Case-insensitive literal search
//! const regexMatches = doc.find("\\d+", true, true); // Case-sensitive regex search
//! ```

pub mod document;
pub mod errors;
pub mod events;

// Re-export WasmDocument for easier access
pub use document::WasmDocument;
