packages:
  - packages/*
  - examples/*

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - esbuild
  - svelte-preprocess

shared-workspace-lockfile: true

strict-peer-dependencies: false
